# Generated by Django 6.0.6 on 2026-06-12 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_pressure_sys', models.IntegerField(help_text='Systolic Blood Pressure (mmHg)')),
                ('blood_pressure_dia', models.IntegerField(help_text='Diastolic Blood Pressure (mmHg)')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(help_text='Daily sleep duration')),
                ('physical_activity_min', models.IntegerField(help_text='Active minutes per day')),
                ('diet_quality_score', models.IntegerField(help_text='Diet score from 0-100')),
                ('vaping_status', models.BooleanField(default=False, help_text='True if uses e-cigarettes/vaping')),
                ('stress_level', models.IntegerField(help_text='Stress scale from 1-10')),
                ('resting_heart_rate', models.FloatField(blank=True, help_text='Extracted via SciPy from wearable file', null=True)),
                ('overall_cvh_score', models.FloatField(blank=True, help_text='Composite AHA 0-100 score', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
