# Generated by Django 6.0.6 on 2026-06-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='diet_quality_score',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='physical_activity_min',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='vaping_status',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='bp_medication',
            field=models.BooleanField(default=False, help_text='True if using antihypertensive medication (-20 pts penalty)'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='moderate_activity_min',
            field=models.IntegerField(default=0, help_text='Moderate physical activity minutes per week'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='nicotine_status',
            field=models.CharField(choices=[('never', 'Never smoked/vaped'), ('quit_5y', 'Quit >= 5 years'), ('quit_1_5y', 'Quit 1 to < 5 years'), ('vaping_or_quit_1y', 'Current Vaping or Quit < 1 year'), ('traditional', 'Current traditional smoking')], default='never', help_text='Nicotine exposure level', max_length=30),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='secondhand_smoke',
            field=models.BooleanField(default=False, help_text='Regular exposure to secondhand smoke (-20 pts penalty)'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='vigorous_activity_min',
            field=models.IntegerField(default=0, help_text='Vigorous physical activity minutes per week'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='bmi',
            field=models.FloatField(blank=True, help_text='Calculated via Asian Population Standard', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='overall_cvh_score',
            field=models.FloatField(blank=True, help_text='Composite AHA 0-100 score (Unweighted average of 5 components)', null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='sleep_hours',
            field=models.FloatField(help_text='Daily sleep duration (8th formal metric)'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='stress_level',
            field=models.IntegerField(help_text='Psychological Stress scale from 1-10'),
        ),
    ]
