# Generated by Django 6.0.6 on 2026-06-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0002_remove_healthrecord_diet_quality_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='age',
            field=models.IntegerField(default=25, help_text='Age of the user for health calculations'),
        ),
    ]
