# Generated by Django 6.0.6 on 2026-06-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0003_healthrecord_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='chart_data',
            field=models.JSONField(blank=True, help_text='Stored downsampled waveform chart data', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='hr_color',
            field=models.CharField(default='green', help_text='Color alert level for UI mapping', max_length=10),
        ),
    ]
